version: "3.8"
services:
  rakuten:
    user: "1000:1000"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rakuten
    ports:
      - "9000:9000"
    volumes:
      - ./:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      - JUPYTER_TOKEN=rakuten123
    restart: unless-stopped
