_wandb:
    value:
        cli_version: 0.23.1
        e:
            fjmglwyzy5qzxqpocbgo3wku9w914gkt:
                codePath: /workspace/notebooks/image/02_resnet50_training.ipynb
                codePathLocal: 02_resnet50_training.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "982240026624"
                        used: "400007839744"
                email: xiaosong.dev@gmail.com
                executable: /usr/local/bin/python
                git:
                    commit: b703bb171bc389881790344123b31ad383eb8b9c
                    remote: git@github.com:ByteVoyageur/ml_rakuten.git
                gpu: NVIDIA GeForce RTX 3060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 4864
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3060 Ti
                      uuid: GPU-cd354ac7-301e-a4f5-438d-4441f7f89fdc
                host: 9c8cc5eb3b24
                memory:
                    total: "33526042624"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.41
                program: /workspace/notebooks/image/02_resnet50_training.ipynb
                python: CPython 3.11.14
                root: /workspace/notebooks/image
                startedAt: "2025-12-20T18:21:12.197599Z"
                writerId: fjmglwyzy5qzxqpocbgo3wku9w914gkt
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.14
            "5": 0.23.1
            "8":
                - 1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 64
checkpoint_dir:
    value: /workspace/checkpoints/resnet50_production
data_dir:
    value: /workspace/data
device:
    value: cuda
early_stopping_patience:
    value: 5
img_dir:
    value: /workspace/data/images/image_train
img_size:
    value: 224
learning_rate:
    value: 0.001
momentum:
    value: 0.9
num_epochs:
    value: 30
num_workers:
    value: 4
random_state:
    value: 42
use_amp:
    value: true
val_split:
    value: 0.15
weight_decay:
    value: 0.0001
