_wandb:
    value:
        cli_version: 0.23.1
        e:
            nyjqmgn4g2aodlwtahchj83dbiq6rmlr:
                codePath: /workspace/notebooks/image/03_ViT_training.ipynb
                codePathLocal: 03_ViT_training.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "982240026624"
                        used: "402092478464"
                email: xiaosong.dev@gmail.com
                executable: /usr/local/bin/python
                git:
                    commit: b703bb171bc389881790344123b31ad383eb8b9c
                    remote: git@github.com:ByteVoyageur/ml_rakuten.git
                gpu: NVIDIA GeForce RTX 3060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 4864
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3060 Ti
                      uuid: GPU-cd354ac7-301e-a4f5-438d-4441f7f89fdc
                host: 9c8cc5eb3b24
                memory:
                    total: "33526034432"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.41
                program: /workspace/notebooks/image/03_ViT_training.ipynb
                python: CPython 3.11.14
                root: /workspace/notebooks/image
                startedAt: "2025-12-21T10:28:46.602441Z"
                writerId: nyjqmgn4g2aodlwtahchj83dbiq6rmlr
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.14
            "5": 0.23.1
            "6": 4.57.3
            "8":
                - 1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 32
checkpoint_dir:
    value: /workspace/checkpoints/vit_production
data_dir:
    value: /workspace/data
device:
    value: cuda
early_stopping_patience:
    value: 3
img_dir:
    value: /workspace/data/images/image_train
img_size:
    value: 224
learning_rate:
    value: 2e-05
model_name:
    value: google/vit-base-patch16-224
num_epochs:
    value: 20
num_workers:
    value: 2
random_state:
    value: 42
use_amp:
    value: true
val_split:
    value: 0.15
warmup_ratio:
    value: 0.1
weight_decay:
    value: 0.05
